# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-09-14 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('customer_uid', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=45)),
                ('customer_location', models.CharField(max_length=45)),
            ],
            options={
                'managed': False,
                'db_table': 'customer_info',
            },
        ),
    ]
