# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-09-10 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer1_incidents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snow_id', models.CharField(max_length=20)),
                ('number', models.CharField(max_length=10)),
                ('state', models.IntegerField()),
                ('category', models.CharField(max_length=20)),
                ('priority', models.IntegerField()),
                ('date_created', models.DateTimeField()),
                ('opened_by', models.CharField(max_length=20)),
                ('assigned_to', models.CharField(max_length=20)),
                ('short_desc', models.CharField(max_length=30)),
            ],
        ),
    ]
